# Generated by Django 4.1.6 on 2023-03-27 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='commented_posts',
        ),
        migrations.RemoveField(
            model_name='account',
            name='liked_posts',
        ),
    ]
